export const ai = [
    {
        key: 'expiry_date',
        value: 'Expiration Date',
        aicode: '17',
        type: 'date',
        description: 'The last safe date to use the product.'
    },
    {
        key: 'batch_no',
        value: 'Batch Number',
        aicode: '10',
        description: 'Unique identifier for a production batch (traceability).'
    },
    {
        key: 'production_date',
        value: 'Production Date',
        aicode: '11',
        type: 'date',
        description: 'Date when the product was manufactured.'
    },
    {
        key: 'packaging_date',
        value: 'Packaging Date',
        aicode: '13',
        type: 'date',
        description: 'Date when the product was packaged.'
    },
    {
        key: 'best_before_date',
        value: 'Best Before Date',
        aicode: '15',
        type: 'date',
        description: 'Recommended date for best quality (not safety).'
    },
    {
        key: 'serial_no',
        value: 'Serial No',
        aicode: '21',
        description: 'Unique ID for an individual product unit.'
    }
];

export  const gs1ApplicationIdentifiers = [
        { key: '00', value: 'Serial Shipping Container Code (SSCC)' },
        { key: '01', value: 'Global Trade Item Number (GTIN)' },
        { key: '253', value: 'Global Document Type Identifier (GDTI)' },
        { key: '255', value: 'Global Coupon Number (GCN)' },
        { key: '401', value: 'Global Identification Number for Consignment (GINC)' },
        { key: '402', value: 'Global Shipment Identification Number (GSIN)' },
        { key: '414', value: 'Identification of a physical location - Global Location Number' },
        { key: '417', value: 'Party GLN' },
        { key: '8003', value: 'Global Returnable Asset Identifier (GRAI)' },
        { key: '8004', value: 'Global Individual Asset Identifier (GIAI)' },
        { key: '8006', value: 'Identification of an individual trade item piece' },
        { key: '8010', value: 'Component/Part Identifier (CPID)' },
        { key: '8013', value: 'Global Model Number (GMN)' },
        { key: '8017', value: 'Global Service Relation Number - Provider' },
        { key: '8018', value: 'Global Service Relation Number - Recipient' }
    ];


 export const gs1ApplicationIndicators: { key: string; value: string }[] = [
    { key: "00", value: "(00) Serial Shipping Container Code (SSCC)" },
    { key: "01", value: "(01) Global Trade Item Number (GTIN)" },
    { key: "02", value: "(02) GTIN of contained trade items" },
    // { key: "10", value: "(10) Batch or lot number" },
    { key: "11", value: "(11) Production date" },
    { key: "12", value: "(12) Due date for payment slip" },
    { key: "13", value: "(13) Packaging date" },
    { key: "15", value: "(15) Best before date" },
    { key: "16", value: "(16) Sell by date" },
    { key: "17", value: "(17) Expiration date" },
    { key: "20", value: "(20) Internal product variant" },
    // { key: "21", value: "(21) Serial number" },
    // { key: "22", value: "(22) Consumer product variant" },
    { key: "235", value: "(235) TPX (GTIN extension)" },
    { key: "240", value: "(240) Additional product ID" },
    { key: "241", value: "(241) Customer part number" },
    { key: "242", value: "(242) Made-to-Order variation number" },
    { key: "243", value: "(243) Packaging component number" },
    { key: "250", value: "(250) Secondary serial number" },
    { key: "251", value: "(251) Reference to source entity" },
    { key: "253", value: "(253) Global Document Type Identifier (GDTI)" },
    { key: "254", value: "(254) GLN extension component" },
    { key: "255", value: "(255) Global Coupon Number (GCN)" },
    { key: "30", value: "(30) Variable count of items" },
    { key: "310", value: "(310) Net weight, kilograms" },
    { key: "311", value: "(311) Length, meters" },
    { key: "312", value: "(312) Width, meters" },
    { key: "313", value: "(313) Height, meters" },
    { key: "314", value: "(314) Area, square meters" },
    { key: "315", value: "(315) Net volume, liters" },
    { key: "316", value: "(316) Net volume, cubic meters" },
    { key: "320", value: "(320) Net weight, pounds" },
    { key: "321", value: "(321) Length, inches" },
    { key: "322", value: "(322) Length, feet" },
    { key: "323", value: "(323) Length, yards" },
    { key: "324", value: "(324) Width, inches" },
    { key: "325", value: "(325) Width, feet" },
    { key: "326", value: "(326) Width, yards" },
    { key: "327", value: "(327) Height, inches" },
    { key: "328", value: "(328) Height, feet" },
    { key: "329", value: "(329) Height, yards" },
    { key: "330", value: "(330) Logistic weight, kilograms" },
    { key: "331", value: "(331) Length, meters" },
    { key: "332", value: "(332) Width, meters" },
    { key: "333", value: "(333) Height, meters" },
    { key: "334", value: "(334) Area, square meters" },
    { key: "335", value: "(335) Logistic volume, liters" },
    { key: "336", value: "(336) Logistic volume, cubic meters" },
    { key: "337", value: "(337) Kilograms per square meter" },
    { key: "340", value: "(340) Logistic weight, pounds" },
    { key: "341", value: "(341) Length, inches" },
    { key: "342", value: "(342) Length, feet" },
    { key: "343", value: "(343) Length, yards" },
    { key: "344", value: "(344) Width, inches" },
    { key: "345", value: "(345) Width, feet" },
    { key: "346", value: "(346) Width, yards" },
    { key: "347", value: "(347) Height, inches" },
    { key: "348", value: "(348) Height, feet" },
    { key: "349", value: "(349) Height, yards" },
    { key: "350", value: "(350) Area, square inches" },
    { key: "351", value: "(351) Area, square feet" },
    { key: "352", value: "(352) Area, square yards" },
    { key: "353", value: "(353) Net weight, troy ounces" },
    { key: "354", value: "(354) Net weight, ounces" },
    { key: "355", value: "(355) Net volume, quarts" },
    { key: "356", value: "(356) Net volume, gallons U.S." },
    { key: "357", value: "(357) Logistic volume, quarts" },
    { key: "358", value: "(358) Logistic volume, gallons U.S." },
    { key: "359", value: "(359) Net volume, cubic inches" },
    { key: "360", value: "(360) Net volume, cubic feet" },
    { key: "361", value: "(361) Net volume, cubic yards" },
    { key: "362", value: "(362) Logistic volume, cubic inches" },
    { key: "363", value: "(363) Logistic volume, cubic feet" },
    { key: "364", value: "(364) Logistic volume, cubic yards" },
    { key: "37", value: "(37) Count of trade items in logistic unit" },
    { key: "390", value: "(390) Amount payable (single currency)" },
    { key: "391", value: "(391) Amount payable with currency code" },
    { key: "392", value: "(392) Amount payable for variable measure" },
    { key: "393", value: "(393) Amount payable for variable measure with currency" },
    { key: "394", value: "(394) Percentage discount of a coupon" },
    { key: "395", value: "(395) Amount payable per unit of measure" },
    { key: "400", value: "(400) Customer purchase order number" },
    { key: "401", value: "(401) Global Identification Number for Consignment (GINC)" },
    { key: "402", value: "(402) Global Shipment ID (GSIN)" },
    { key: "403", value: "(403) Routing code" },
    { key: "410", value: "(410) Ship-to GLN" },
    { key: "411", value: "(411) Bill-to GLN" },
    { key: "412", value: "(412) Purchased from GLN" },
    { key: "413", value: "(413) Ship for GLN" },
    { key: "414", value: "(414) Physical location GLN" },
    { key: "415", value: "(415) Invoicing party GLN" },
    { key: "416", value: "(416) Production/service location GLN" },
    { key: "417", value: "(417) Party GLN" },
    { key: "420", value: "(420) Ship-to postal code" },
    { key: "421", value: "(421) Ship-to postal code with country" },
    { key: "422", value: "(422) Country of origin" },
    { key: "423", value: "(423) Country of initial processing" },
    { key: "424", value: "(424) Country of processing" },
    { key: "425", value: "(425) Country of disassembly" },
    { key: "426", value: "(426) Country covering full process chain" },
    { key: "427", value: "(427) Country subdivision of origin" },
    { key: "4300", value: "(4300) Ship-to company name" },
    { key: "4301", value: "(4301) Ship-to contact" },
    { key: "4302", value: "(4302) Ship-to address line 1" },
    { key: "4303", value: "(4303) Ship-to address line 2" },
    { key: "4304", value: "(4304) Ship-to suburb" },
    { key: "4305", value: "(4305) Ship-to locality" },
    { key: "4306", value: "(4306) Ship-to region" },
    { key: "4307", value: "(4307) Ship-to country code" },
    { key: "4308", value: "(4308) Ship-to telephone number" },
    { key: "4309", value: "(4309) Ship-to GEO location" },
    { key: "4310", value: "(4310) Return-to company" },
    { key: "4311", value: "(4311) Return-to contact" },
    { key: "4312", value: "(4312) Return-to address line 1" },
    { key: "4313", value: "(4313) Return-to address line 2" },
    { key: "4314", value: "(4314) Return-to suburb" },
    { key: "4315", value: "(4315) Return-to locality" },
    { key: "4316", value: "(4316) Return-to region" },
    { key: "4317", value: "(4317) Return-to country code" },
    { key: "4318", value: "(4318) Return-to postal code" },
    { key: "4319", value: "(4319) Return-to telephone number" },
    { key: "4320", value: "(4320) Service code description" },
    { key: "4321", value: "(4321) Dangerous goods flag" },
    { key: "4322", value: "(4322) Authority to leave flag" },
    { key: "4323", value: "(4323) Signature required flag" },
    { key: "4324", value: "(4324) Not before delivery date/time" },
    { key: "4325", value: "(4325) Not after delivery date/time" },
    { key: "4326", value: "(4326) Release date" },
    { key: "4330", value: "(4330) Max temp (Fahrenheit)" },
    { key: "4331", value: "(4331) Max temp (Celsius)" },
    { key: "4332", value: "(4332) Min temp (Fahrenheit)" },
    { key: "4333", value: "(4333) Min temp (Celsius)" },
    { key: "7001", value: "(7001) NATO Stock Number (NSN)" },
    { key: "7002", value: "(7002) UNECE meat classification" },
    { key: "7003", value: "(7003) Expiration date and time" },
    { key: "7004", value: "(7004) Active potency" },
    { key: "7005", value: "(7005) Catch area" },
    { key: "7006", value: "(7006) First freeze date" },
    { key: "7007", value: "(7007) Harvest date" },
    { key: "7008", value: "(7008) Species for fishery purposes" },
    { key: "7009", value: "(7009) Fishing gear type" },
    { key: "7010", value: "(7010) Production method" },
    { key: "7011", value: "(7011) Test by date" },
    { key: "7020", value: "(7020) Refurbishment lot ID" },
    { key: "7021", value: "(7021) Functional status" },
    { key: "7022", value: "(7022) Revision status" },
    { key: "7023", value: "(7023) Global Individual Asset Identifier of an assembly" },
    { key: "703", value: "(703) Number of processor with country code" },
    { key: "7040", value: "(7040) GS1 UIC with Extension 1 and Importer index" },
    { key: "710", value: "(710) NHRN - Germany PZN" },
    { key: "711", value: "(711) NHRN - France CIP" },
    { key: "712", value: "(712) NHRN - Spain CN" },
    { key: "713", value: "(713) NHRN - Brasil DRN" },
    { key: "714", value: "(714) NHRN - Portugal AIM" },
    { key: "715", value: "(715) NHRN - USA NDC" },
    { key: "723", value: "(723) Certification reference" },
    { key: "7240", value: "(7240) Protocol ID" },
    { key: "7241", value: "(7241) AIDC media type" },
    { key: "7242", value: "(7242) Version Control Number (VCN)" },
    { key: "8001", value: "(8001) Roll products dimensions" },
    { key: "8002", value: "(8002) Cellular mobile ID" },
    { key: "8003", value: "(8003) Global Returnable Asset ID (GRAI)" },
    { key: "8004", value: "(8004) Global Individual Asset ID (GIAI)" },
    { key: "8005", value: "(8005) Price per unit" },
    { key: "8006", value: "(8006) Individual trade item piece" },
    { key: "8007", value: "(8007) IBAN" },
    { key: "8008", value: "(8008) Production date/time" },
    { key: "8009", value: "(8009) Optical sensor indicator" },
    { key: "8010", value: "(8010) Component/Part ID (CPID)" },
    { key: "8011", value: "(8011) Component serial number" },
    { key: "8012", value: "(8012) Software version" },
    { key: "8013", value: "(8013) Global Model Number (GMN)" },
    { key: "8017", value: "(8017) GSRN Provider" },
    { key: "8018", value: "(8018) GSRN Recipient" },
    { key: "8019", value: "(8019) Service Relation Instance Number" },
    { key: "8020", value: "(8020) Payment slip reference" },
    { key: "8026", value: "(8026) ITIP in logistic unit" },
    { key: "8030", value: "(8030) Digital Signature" },
    { key: "8110", value: "(8110) Coupon code (North America)" },
    { key: "8111", value: "(8111) Loyalty points" },
    { key: "8112", value: "(8112) Positive offer coupon" },
    { key: "8200", value: "(8200) Extended packaging URL" },
    { key: "90", value: "(90) Mutually agreed information" },
    { key: "91", value: "(91) Company internal info 1" },
    { key: "92", value: "(92) Company internal info 2" },
    { key: "93", value: "(93) Company internal info 3" },
    { key: "94", value: "(94) Company internal info 4" },
    { key: "95", value: "(95) Company internal info 5" },
    { key: "96", value: "(96) Company internal info 6" },
    { key: "97", value: "(97) Company internal info 7" },
    { key: "98", value: "(98) Company internal info 8" },
    { key: "99", value: "(99) Company internal info 9" }
];


    const gs1ApplicationIndicatorsOld: { key: string; value: string }[] = [
        { key: "00", value: "(00) Serial Shipping Container Code (SSCC)" },
        { key: "01", value: "(01) Global Trade Item Number (GTIN)" },
        { key: "02", value: "(02) GTIN of contained trade items" },
        // { key: "10", value: "(10) Batch or lot number" },
        { key: "11", value: "(11) Production date" },
        { key: "12", value: "(12) Due date for payment slip" },
        { key: "13", value: "(13) Packaging date" },
        { key: "15", value: "(15) Best before date" },
        { key: "16", value: "(16) Sell by date" },
        { key: "17", value: "(17) Expiration date" },
        { key: "20", value: "(20) Internal product variant" },
        // { key: "21", value: "(21) Serial number" },
        // { key: "22", value: "(22) Consumer product variant" },
        { key: "235", value: "(235) TPX (GTIN extension)" },
        { key: "240", value: "(240) Additional product ID" },
        { key: "241", value: "(241) Customer part number" },
        { key: "242", value: "(242) Made-to-Order variation number" },
        { key: "243", value: "(243) Packaging component number" },
        { key: "250", value: "(250) Secondary serial number" },
        { key: "251", value: "(251) Reference to source entity" },
        { key: "253", value: "(253) Global Document Type Identifier (GDTI)" },
        { key: "254", value: "(254) GLN extension component" },
        { key: "255", value: "(255) Global Coupon Number (GCN)" },
        { key: "30", value: "(30) Variable count of items" },
        { key: "310", value: "(310) Net weight, kilograms" },
        { key: "311", value: "(311) Length, meters" },
        { key: "312", value: "(312) Width, meters" },
        { key: "37", value: "(37) Count of trade items in logistic unit" },
        { key: "390", value: "(390) Amount payable (single currency)" },
        { key: "391", value: "(391) Amount payable with currency code" },
        { key: "400", value: "(400) Customer purchase order number" },
        { key: "401", value: "(401) Global Identification Number for Consignment (GINC)" },
        { key: "402", value: "(402) Global Shipment ID (GSIN)" },
        { key: "403", value: "(403) Routing code" },
        { key: "410", value: "(410) Ship-to GLN" },
        { key: "411", value: "(411) Bill-to GLN" },
        { key: "420", value: "(420) Ship-to postal code" },
        { key: "421", value: "(421) Ship-to postal code with country" },
        { key: "4300", value: "(4300) Ship-to company name" },
        { key: "4301", value: "(4301) Ship-to contact" },
        { key: "4310", value: "(4310) Return-to company" },
        { key: "4320", value: "(4320) Service code description" },
        { key: "4330", value: "(4330) Max temp (Fahrenheit)" },
        { key: "7001", value: "(7001) NATO Stock Number (NSN)" },
        { key: "7002", value: "(7002) UNECE meat classification" },
        { key: "8001", value: "(8001) Roll products dimensions" },
        { key: "8002", value: "(8002) Cellular mobile ID" },
        { key: "8003", value: "(8003) Global Returnable Asset ID (GRAI)" },
        { key: "8004", value: "(8004) Global Individual Asset ID (GIAI)" },
        { key: "8005", value: "(8005) Price per unit" },
        { key: "8006", value: "(8006) Individual trade item piece" },
        { key: "8007", value: "(8007) IBAN" },
        { key: "8008", value: "(8008) Production date/time" },
        { key: "8009", value: "(8009) Optical sensor indicator" },
        { key: "8010", value: "(8010) Component/Part ID (CPID)" },
        { key: "8011", value: "(8011) Component serial number" },
        { key: "8012", value: "(8012) Software version" },
        { key: "8013", value: "(8013) Global Model Number (GMN)" },
        { key: "8017", value: "(8017) GSRN Provider" },
        { key: "8018", value: "(8018) GSRN Recipient" },
        { key: "8019", value: "(8019) Service Relation Instance Number" },
        { key: "8020", value: "(8020) Payment slip reference" },
        { key: "8026", value: "(8026) ITIP in logistic unit" },
        { key: "8030", value: "(8030) Digital Signature" },
        { key: "8110", value: "(8110) Coupon code (North America)" },
        { key: "8111", value: "(8111) Loyalty points" },
        { key: "8112", value: "(8112) Positive offer coupon" },
        { key: "8200", value: "(8200) Extended packaging URL" },
        { key: "90", value: "(90) Mutually agreed information" },
        { key: "91", value: "(91) Company internal info 1" },
        { key: "99", value: "(99) Company internal info 9" }
    ];
