export const supportedFormats = [
    'qr', 'aztec', 'data-matrix',
    'ean-13', 'ean-8', 'code-128',
    'code-39', 'code-93', 'codabar',
    'itf', 'pdf-417', 'rss-14',
    'rss-expanded', 'upc-e', 'rss-limited'
];
// Barcode types shown in the “Choose symbology” dropdown
export const barcodeOptions = [
  { key: 'azteccode',                   value: 'Aztec Code' },       
  { key: 'code128',                    value: 'Code-128' },         
  { key: 'dotcode',                    value: 'DotCode' },
  { key: 'ean13',                      value: 'EAN-13' },
  { key: 'ean13composite',             value: 'EAN-13 Composite' },
  { key: 'ean14',                      value: 'EAN-14' },
  { key: 'ean2',                       value: 'EAN-2 (2 digit addon)' },
  { key: 'ean5',                       value: 'EAN-5 (5 digit addon)' },
  { key: 'ean8',                       value: 'EAN-8' },
  { key: 'ean8composite',              value: 'EAN-8 Composite' },
  { key: 'flattermarken',              value: 'Flattermarken' },
  { key: 'gs1-128',                    value: 'GS1-128' },
  { key: 'gs1-128composite',           value: 'GS1-128 Composite' },
  { key: 'gs1-cc',                     value: 'GS1 Composite 2D Component' },
  { key: 'gs1datamatrix',              value: 'GS1 Data Matrix' },
  { key: 'gs1datamatrixrectangular',   value: 'GS1 Data Matrix Rectangular' },
  { key: 'gs1dldatamatrix',            value: 'GS1 Digital Link Data Matrix' },
  { key: 'gs1dlqrcode',                value: 'GS1 Digital Link QR Code' },
  { key: 'gs1dotcode',                 value: 'GS1 DotCode' },
  { key: 'gs1northamericancoupon',     value: 'GS1 North American Coupon' },
  { key: 'gs1qrcode',                  value: 'GS1 QR Code' },
  { key: 'hanxin',                     value: 'Han Xin Code' },
  { key: 'hibcazteccode',              value: 'HIBC Aztec Code' },
  { key: 'hibccodablockf',             value: 'HIBC Codablock F' },
  { key: 'hibccode128',                value: 'HIBC Code 128' },
  { key: 'hibccode39',                 value: 'HIBC Code 39' },
  { key: 'hibcdatamatrix',             value: 'HIBC Data Matrix' },
  { key: 'hibcdatamatrixrectangular',  value: 'HIBC Data Matrix Rectangular' },
  { key: 'hibcmicropdf417',            value: 'HIBC MicroPDF417' },
  { key: 'hibcpdf417',                 value: 'HIBC PDF417' },
  { key: 'hibcqrcode',                 value: 'HIBC QR Code' },
  { key: 'iata2of5',                   value: 'IATA 2 of 5' },
  { key: 'identcode',                  value: 'Deutsche Post Identcode' },
  { key: 'industrial2of5',             value: 'Industrial 2 of 5' },
  { key: 'interleaved2of5',            value: 'Interleaved 2 of 5 (ITF)' },
  { key: 'isbn',                       value: 'ISBN' },
  { key: 'ismn',                       value: 'ISMN' },
  { key: 'issn',                       value: 'ISSN' },
  { key: 'itf14',                      value: 'ITF-14' },
  { key: 'jabcode',                    value: 'JAB Code (Beta)' },
  { key: 'japanpost',                  value: 'Japan Post 4 State Customer Code' },
  { key: 'kix',                        value: 'Royal Dutch TPG Post KIX' },
  { key: 'leitcode',                   value: 'Deutsche Post Leitcode' },
  { key: 'mailmark',                   value: 'Royal Mail Mailmark' },
  { key: 'mands',                      value: 'Marks & Spencer' },
  { key: 'matrix2of5',                 value: 'Matrix 2 of 5' },
  { key: 'maxicode',                   value: 'MaxiCode' },
  { key: 'micropdf417',                value: 'MicroPDF417' },
  { key: 'microqrcode',                value: 'Micro QR Code' },
  { key: 'msi',                        value: 'MSI Modified Plessey' },
  { key: 'onecode',                    value: 'USPS Intelligent Mail' },
  { key: 'pdf417',                     value: 'PDF417' },
  { key: 'pdf417compact',              value: 'Compact PDF417' },
  { key: 'pharmacode',                 value: 'Pharmaceutical Binary Code' },
  { key: 'pharmacode2',                value: 'Two-track Pharmacode' },
  { key: 'planet',                     value: 'USPS PLANET' },
  { key: 'plessey',                    value: 'Plessey UK' },
  { key: 'posicode',                   value: 'PosiCode' },
  { key: 'postnet',                    value: 'USPS POSTNET' },
  { key: 'pzn',                        value: 'Pharmazentralnummer (PZN)' },
  { key: 'qrcode',                     value: 'QR Code' },
  { key: 'rationalizedCodabar',        value: 'Codabar' },
  { key: 'raw',                        value: 'Custom 1D symbology' },
  { key: 'rectangularmicroqrcode',     value: 'Rectangular Micro QR Code' },
  { key: 'royalmail',                  value: 'Royal Mail 4 State Customer Code' },
  { key: 'sscc18',                     value: 'SSCC-18' },
  { key: 'swissqrcode',                value: 'Swiss QR Code' },
  { key: 'symbol',                     value: 'Miscellaneous symbols' },
  { key: 'telepen',                    value: 'Telepen' },
  { key: 'telepennumeric',             value: 'Telepen Numeric' },
  { key: 'ultracode',                  value: 'Ultracode' },
  { key: 'upca',                       value: 'UPC-A' },
  { key: 'upcacomposite',              value: 'UPC-A Composite' },
  { key: 'upce',                       value: 'UPC-E' },
  { key: 'upcecomposite',              value: 'UPC-E Composite' },
] as const;



export const languages = [
  { key: "en", value: "English" },
  { key: "es", value: "Spanish" },
  { key: "fr", value: "French" },
  { key: "de", value: "German" },
  { key: "it", value: "Italian" },
  { key: "pt", value: "Portuguese" },
  { key: "ru", value: "Russian" },
  { key: "zh", value: "Chinese" },
  { key: "ja", value: "Japanese" },
  { key: "ko", value: "Korean" },
  { key: "ar", value: "Arabic" },
  { key: "hi", value: "Hindi" },
  { key: "bn", value: "Bengali" },
  { key: "pa", value: "Punjabi" },
  { key: "tr", value: "Turkish" },
  { key: "nl", value: "Dutch" },
  { key: "sv", value: "Swedish" },
  { key: "fi", value: "Finnish" },
  { key: "da", value: "Danish" },
  { key: "no", value: "Norwegian" },
  { key: "pl", value: "Polish" },
  { key: "uk", value: "Ukrainian" },
  { key: "cs", value: "Czech" },
  { key: "hu", value: "Hungarian" },
  { key: "ro", value: "Romanian" },
  { key: "el", value: "Greek" },
  { key: "th", value: "Thai" },
  { key: "vi", value: "Vietnamese" },
  { key: "id", value: "Indonesian" },
  { key: "ms", value: "Malay" },
  { key: "he", value: "Hebrew" },
  { key: "fa", value: "Persian" },
  { key: "ur", value: "Urdu" },
  { key: "ta", value: "Tamil" },
  { key: "te", value: "Telugu" },
  { key: "mr", value: "Marathi" },
  { key: "gu", value: "Gujarati" },
  { key: "kn", value: "Kannada" },
  { key: "ml", value: "Malayalam" },
  { key: "si", value: "Sinhala" },
  { key: "my", value: "Burmese" },
  { key: "km", value: "Khmer" },
  { key: "lo", value: "Lao" },
  { key: "ne", value: "Nepali" },
  { key: "sd", value: "Sindhi" },
  { key: "am", value: "Amharic" },
  { key: "ti", value: "Tigrinya" },
  { key: "om", value: "Oromo" },
  { key: "so", value: "Somali" },
  { key: "sw", value: "Swahili" },
  { key: "yo", value: "Yoruba" },
  { key: "ig", value: "Igbo" },
  { key: "ha", value: "Hausa" },
  { key: "zu", value: "Zulu" },
  { key: "xh", value: "Xhosa" },
  { key: "af", value: "Afrikaans" },
  { key: "st", value: "Southern Sotho" },
  { key: "tn", value: "Tswana" },
  { key: "ss", value: "Swati" },
  { key: "ve", value: "Venda" },
  { key: "ts", value: "Tsonga" },
  { key: "nr", value: "Ndebele" },
  { key: "az", value: "Azerbaijani" },
  { key: "kk", value: "Kazakh" },
  { key: "uz", value: "Uzbek" },
  { key: "tk", value: "Turkmen" },
  { key: "ky", value: "Kyrgyz" },
  { key: "tg", value: "Tajik" },
  { key: "mn", value: "Mongolian" },
  { key: "ka", value: "Georgian" },
  { key: "hy", value: "Armenian" },
  { key: "iw", value: "Hebrew" },
  { key: "ps", value: "Pashto" },
  { key: "ku", value: "Kurdish" },
  { key: "bo", value: "Tibetan" },
  { key: "dv", value: "Divehi" },
  { key: "ks", value: "Kashmiri" },
  { key: "as", value: "Assamese" },
  { key: "or", value: "Odia" },
  { key: "sa", value: "Sanskrit" },
  { key: "mai", value: "Maithili" },
  { key: "bh", value: "Bihari" },
  { key: "sat", value: "Santali" },
  { key: "kok", value: "Konkani" },
  { key: "doi", value: "Dogri" },
  { key: "mni", value: "Manipuri" },
  { key: "lus", value: "Mizo" },
  { key: "brx", value: "Bodo" },
  { key: "grt", value: "Garo" },
  { key: "kha", value: "Khasi" },
  { key: "mic", value: "Mi'kmaq" },
  { key: "smi", value: "Sami" },
  { key: "ven", value: "Venda" },
  { key: "tso", value: "Tsonga" },
  { key: "nso", value: "Northern Sotho" },
  { key: "tum", value: "Tumbuka" },
  { key: "nya", value: "Nyanja" },
  { key: "sna", value: "Shona" },
  { key: "run", value: "Rundi" },
  { key: "kik", value: "Kikuyu" },
  { key: "lug", value: "Ganda" },
  { key: "nyn", value: "Nyankole" },
  { key: "ach", value: "Acoli" },
  { key: "ada", value: "Adangme" },
  { key: "bem", value: "Bemba" },
  { key: "bin", value: "Edo" },
  { key: "efi", value: "Efik" },
  { key: "ewe", value: "Ewe" },
  { key: "fon", value: "Fon" },
  { key: "gaa", value: "Ga" },
  { key: "gon", value: "Gondi" },
  { key: "ibo", value: "Igbo" },
  { key: "kam", value: "Kamba" },
  { key: "kpe", value: "Kpelle" },
  { key: "kro", value: "Kru" },
  { key: "lua", value: "Luba-Lulua" },
  { key: "luo", value: "Luo" },
  { key: "mos", value: "Mossi" },
  { key: "sag", value: "Sango" },
  { key: "srr", value: "Serer" },
  { key: "sus", value: "Susu" },
  { key: "tem", value: "Timne" },
  { key: "tiv", value: "Tiv" },
  { key: "wol", value: "Wolof" },
  { key: "yor", value: "Yoruba" },
  { key: "zul", value: "Zulu" }
];